use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use bytes::Bytes;
use p256::PublicKey;
use rustls::ClientConfig;
use thiserror::Error;
use usque_crypto::QuicheClientCredentials;

#[derive(Debug, Clone)]
pub struct ConnectOptions {
    pub tls_config: Arc<ClientConfig>,
    pub quiche_credentials: Arc<QuicheClientCredentials>,
    pub insecure: bool,
    pub peer_public_key: PublicKey,
    pub endpoint: SocketAddr,
    pub sni: String,
    pub use_http2: bool,
    pub keepalive_period: Duration,
    pub initial_packet_size: u16,
    pub connect_uri: String,
}

#[derive(Debug, Error)]
pub enum SessionError {
    #[error("session closed")]
    Closed,
    #[error(transparent)]
    Other(#[from] anyhow::Error),
}

/// IP packet session over MASQUE CONNECT-IP.
///
/// The trait speaks in `Bytes` so that the supervisor's reusable
/// scratch buffer can be moved into the datagram writer with no
/// per-packet allocation. Implementations consume the input `Bytes`
/// (do not retain it) but may return a refcounted slice that aliases
/// their internal receive buffer for the inbound path.
#[async_trait]
pub trait PacketSession: Send + Sync {
    /// Read the next IP packet. `None` indicates the session is closed.
    async fn read_packet(&mut self) -> Result<Option<Bytes>, SessionError>;

    /// Send an IP packet. Implementations consume `packet`; callers
    /// must not retain it after the future completes. Returns an
    /// optional ICMP reply generated by the tunnel.
    async fn write_packet(&mut self, packet: Bytes) -> Result<Option<Bytes>, SessionError>;

    async fn close(&mut self) -> Result<(), SessionError>;
}
