use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use bytes::Bytes;
use rustls::ClientConfig;
use thiserror::Error;
use usque_crypto::{PeerPublicKey, QuicheClientCredentials};

#[derive(Debug, Clone)]
pub struct ConnectOptions {
    pub tls_config: Arc<ClientConfig>,
    pub quiche_credentials: Arc<QuicheClientCredentials>,
    pub insecure: bool,
    pub peer_public_key: PeerPublicKey,
    pub endpoint: SocketAddr,
    pub sni: String,
    pub use_http2: bool,
    pub keepalive_period: Duration,
    pub initial_packet_size: u16,
    pub connect_uri: String,
}

#[derive(Debug, Error)]
pub enum SessionError {
    #[error("session closed")]
    Closed,
    #[error(transparent)]
    Other(#[from] anyhow::Error),
}

/// IP packet session over MASQUE CONNECT-IP.
///
/// The outbound path borrows `&[u8]`: every implementation copies
/// the packet into its own reusable scratch to prepend the datagram
/// prefix anyway, so transferring a refcounted `Bytes` only forced
/// the caller (the supervisor) into a fresh `BytesMut` allocation
/// per outbound packet. The inbound path still returns a refcounted
/// `Bytes` that may alias the session's receive buffer (zero copy).
#[async_trait]
pub trait PacketSession: Send + Sync {
    /// Read the next IP packet. `None` indicates the session is closed.
    async fn read_packet(&mut self) -> Result<Option<Bytes>, SessionError>;

    /// Send an IP packet. The packet only needs to stay valid for
    /// the duration of the call. Returns an optional ICMP reply
    /// generated by the tunnel.
    async fn write_packet(&mut self, packet: &[u8]) -> Result<Option<Bytes>, SessionError>;

    async fn close(&mut self) -> Result<(), SessionError>;
}
