use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use p256::PublicKey;
use rustls::ClientConfig;
use thiserror::Error;
use usque_crypto::QuicheClientCredentials;

#[derive(Debug, Clone)]
pub struct ConnectOptions {
    pub tls_config: Arc<ClientConfig>,
    pub quiche_credentials: Arc<QuicheClientCredentials>,
    pub insecure: bool,
    pub peer_public_key: PublicKey,
    pub endpoint: SocketAddr,
    pub sni: String,
    pub use_http2: bool,
    pub keepalive_period: Duration,
    pub initial_packet_size: u16,
    pub connect_uri: String,
}

#[derive(Debug, Error)]
pub enum SessionError {
    #[error("session closed")]
    Closed,
    #[error(transparent)]
    Other(#[from] anyhow::Error),
}

/// IP packet session over MASQUE CONNECT-IP.
#[async_trait]
pub trait PacketSession: Send + Sync {
    async fn read_packet(&mut self, buf: &mut [u8]) -> Result<usize, SessionError>;
    /// Returns optional ICMP reply generated by the tunnel.
    async fn write_packet(&mut self, packet: &[u8]) -> Result<Option<Vec<u8>>, SessionError>;
    async fn close(&mut self) -> Result<(), SessionError>;
}
